export const FETCH_MEASUREMENTS_INTERVAL = 'FETCH_MEASUREMENTS_INTERVAL'
export const FETCH_MEASUREMENTS_INTERVAL_FULFILLED =
	'FETCH_MEASUREMENTS_INTERVAL_FULFILLED'
export const FETCH_MEASUREMENTS_INTERVAL_REJECTED =
	'FETCH_MEASUREMENTS_INTERVAL_REJECTED'

export const FETCH_MEASUREMENTS_LAST = 'FETCH_MEASUREMENTS_LAST'
export const FETCH_MEASUREMENTS_LAST_FULFILLED =
	'FETCH_MEASUREMENTS_LAST_FULFILLED'
export const FETCH_MEASUREMENTS_LAST_REJECTED =
	'FETCH_MEASUREMENTS_LAST_REJECTED'
