export const REFRESH_MEASUREMENTS = 'REFRESH_MEASUREMENTS'

export const FETCH_MEASUREMENTS_GRAPHVIEW = 'FETCH_MEASUREMENTS_GRAPHVIEW'
export const FETCH_MEASUREMENTS_GRAPHVIEW_FULFILLED =
	'FETCH_MEASUREMENTS_GRAPHVIEW_FULFILLED'
export const FETCH_MEASUREMENTS_GRAPHVIEW_REJECTED =
	'FETCH_MEASUREMENTS_GRAPHVIEW_REJECTED'

export const FETCH_MEASUREMENTS_LAST = 'FETCH_MEASUREMENTS_LAST'
export const FETCH_MEASUREMENTS_LAST_FULFILLED =
	'FETCH_MEASUREMENTS_LAST_FULFILLED'
export const FETCH_MEASUREMENTS_LAST_REJECTED =
	'FETCH_MEASUREMENTS_LAST_REJECTED'

export const FETCH_MEASUREMENTS_AGGREGATE = 'FETCH_MEASUREMENTS_AGGREGATE'
export const FETCH_MEASUREMENTS_AGGREGATE_FULFILLED =
	'FETCH_MEASUREMENTS_AGGREGATE_FULFILLED'
export const FETCH_MEASUREMENTS_AGGREGATE_REJECTED =
	'FETCH_MEASUREMENTS_AGGREGAT_REJECTED'
