export const ADD_SUBSCRIPTIONS = 'ADD_SUBSCRIPTIONS'
export const ADD_SUBSCRIPTIONS_FULFILLED = 'ADD_SUBSCRIPTIONS_FULFILLED'

export const REMOVE_SUBSCRIPTIONS = 'REMOVE_SUBSCRIPTIONS'
export const REMOVE_SUBSCRIPTIONS_FULFILLED = 'REMOVE_SUBSCRIPTIONS_FULFILLED'

export const INCOMING_DATA = 'INCOMING_DATA'
